# Generated by Django 2.2.5 on 2019-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190921_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='slug',
            field=models.SlugField(default='username', max_length=200, unique=True),
        ),
    ]
