# Generated by Django 2.2.6 on 2019-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='chat_id',
            field=models.CharField(default='id003', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
