# Generated by Django 2.2.6 on 2019-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_followers_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='chat_id',
            field=models.CharField(max_length=200),
        ),
    ]
